[package]
description = "Standalone Pyth oracle ingester service"
edition = { workspace = true }
license = { workspace = true }
name = "pyth-ingester"
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "pyth-ingester"
path = "src/main.rs"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
byteorder = "1"
bytes = { workspace = true }
dotenvy = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-sdk = { workspace = true }
parking_lot = { workspace = true }
price-oracle-ipc = { workspace = true }
pythnet-sdk = "3.0.0"
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
