// ABOUTME: Round-trip, golden-vector and invalid-input tests for the hedera-vm
// ABOUTME: withdrawal codec and the Hedera transaction body it signs.

import { bytesToHex } from "viem"
import { describe, expect, test } from "vitest"

import {
  DecodedHederaVmWithdrawal,
  decodeWithdrawal,
  encodeWithdrawal,
  getDecodedWithdrawalAmount,
  getDecodedWithdrawalCurrency,
  getDecodedWithdrawalId,
  getDecodedWithdrawalRecipient,
} from "../src/messages/v2.1/depository-withdrawal"
import { getHederaVmTransactionBody } from "../src/messages/v2.1/withdrawals/hedera-vm"
import { HEDERA_HBAR_TOKEN_ID, HEDERA_MAINNET_USDC_TOKEN_ID } from "../src"

type Withdrawal = DecodedHederaVmWithdrawal["withdrawal"]

const BASE: Withdrawal = {
  payer: "0.0.98",
  sender: "0.0.1001",
  receiver: "0.0.2002",
  amount: "500000000",
  token: HEDERA_HBAR_TOKEN_ID,
  nodeAccount: "0.0.3",
  validStart: "1700000000.123456789",
  validDurationSeconds: 120,
  maxTransactionFee: "100000000",
}

const withdrawal = (overrides: Partial<Withdrawal> = {}): Withdrawal => ({
  ...BASE,
  ...overrides,
})

const decoded = (
  overrides: Partial<Withdrawal> = {}
): DecodedHederaVmWithdrawal => ({
  vmType: "hedera-vm",
  withdrawal: withdrawal(overrides),
})

const body = (overrides: Partial<Withdrawal> = {}): string =>
  bytesToHex(getHederaVmTransactionBody(withdrawal(overrides)))

// Golden transaction bodies, generated by the Hedera JavaScript SDK v2.81.0
// (`TransferTransaction ... .freeze()`, taking `bodyBytes`) for the same
// transfers. HederaVmPayloadBuilder.sol pins the identical vectors, so all
// three implementations agree byte for byte.
const HBAR_BODY =
  "0x0a170a0b0880e2cfaa0610959aef3a1206080010001862180012060800100018031880c2d72f22020878320072280a260a110a070800100018e90710ff93ebdc0318000a110a070800100018d20f108094ebdc031800"
const USDC_BODY =
  "0x0a170a0b0880e2cfaa0610959aef3a1206080010001862180012060800100018031880c2d72f22020878320072300a00122c0a0808001000189af11b120f0a070800100018e90710ff887a1800120f0a070800100018d20f1080897a1800"
const HBAR_BODY_RECEIVER_BELOW_SENDER =
  "0x0a170a0b0880e2cfaa0610959aef3a1206080010001862180012060800100018031880c2d72f22020878320072200a1e0a0d0a070800100018e907100e18000a0d0a070800100018d20f100d1800"
const USDC_BODY_RECEIVER_BELOW_SENDER =
  "0x0a170a0b0880e2cfaa0610959aef3a1206080010001862180012060800100018031880c2d72f220208783200722c0a0012280a0808001000189af11b120c0a0608001000180510021800120e0a080800100018bf843d10011800"
const HBAR_BODY_LARGE_VALUES =
  "0x0a170a0b0880e2cfaa0610959aef3a1206080010001862180012060800100018031880c2d72f22020878320072380a360a150a0608001000180110ffff9fcfc8e0c8e38a0118000a1d0a0e0800100018ffffffffffffffff7f108080a0cfc8e0c8e38a011800"

// keccak256 of the bodies above: what Hedera verifies an ECDSA secp256k1
// signature against, and what the allocator signs.
const HBAR_DIGEST =
  "0xa45da741578cab3c272b3d84859bb0b44f187b8972af233c985ba71e35e0b343"
const USDC_DIGEST =
  "0x6ff48edd5b88686908911c368548adbf4eb5e332415e890bd15568e00b510c4f"

describe("hedera-vm withdrawal codec", () => {
  test.each([
    ["HBAR", HEDERA_HBAR_TOKEN_ID, "500000000"],
    ["USDC", HEDERA_MAINNET_USDC_TOKEN_ID, "1000000"],
  ])("round-trips a %s withdrawal", (_name, token, amount) => {
    const original = decoded({ token, amount })
    expect(decodeWithdrawal(encodeWithdrawal(original), "hedera-vm")).toEqual(
      original
    )
  })

  test("round-trips the largest representable values", () => {
    const original = decoded({
      sender: "0.0.1",
      receiver: "0.0.9223372036854775807",
      amount: "5000000000000000000",
      validStart: "1700000000.999999999",
      validDurationSeconds: 180,
    })
    expect(decodeWithdrawal(encodeWithdrawal(original), "hedera-vm")).toEqual(
      original
    )
  })

  test("exposes the withdrawal's currency, amount and recipient", () => {
    expect(getDecodedWithdrawalCurrency(decoded())).toBe(HEDERA_HBAR_TOKEN_ID)
    expect(
      getDecodedWithdrawalCurrency(
        decoded({ token: HEDERA_MAINNET_USDC_TOKEN_ID })
      )
    ).toBe(HEDERA_MAINNET_USDC_TOKEN_ID)
    expect(getDecodedWithdrawalAmount(decoded())).toBe("500000000")
    expect(getDecodedWithdrawalRecipient(decoded())).toBe("0.0.2002")
  })

  test("normalizes a long-zero address to the account id it encodes", () => {
    // The receiver's long-zero EVM address is the same identity as `0.0.2002`,
    // so it produces the same payload.
    const viaLongZero = decoded({
      receiver: "0x00000000000000000000000000000000000007d2",
    })
    expect(encodeWithdrawal(viaLongZero)).toBe(encodeWithdrawal(decoded()))
  })
})

describe("hedera-vm transaction body", () => {
  test("matches the Hedera SDK for an HBAR transfer", () => {
    expect(body()).toBe(HBAR_BODY)
  })

  test("matches the Hedera SDK for a USDC transfer", () => {
    expect(
      body({ token: HEDERA_MAINNET_USDC_TOKEN_ID, amount: "1000000" })
    ).toBe(USDC_BODY)
  })

  // Hedera orders transfer entries by ascending account number rather than
  // debit-first, so a receiver below the sender swaps the two entries. The fee
  // payer never appears in the transfer list, so it plays no part in the order.
  test("orders transfer entries by ascending account number", () => {
    expect(
      body({ sender: "0.0.2002", receiver: "0.0.1001", amount: "7" })
    ).toBe(HBAR_BODY_RECEIVER_BELOW_SENDER)
    expect(
      body({
        sender: "0.0.999999",
        receiver: "0.0.5",
        amount: "1",
        token: HEDERA_MAINNET_USDC_TOKEN_ID,
      })
    ).toBe(USDC_BODY_RECEIVER_BELOW_SENDER)
  })

  test("matches the Hedera SDK for multi-byte varint values", () => {
    expect(
      body({
        sender: "0.0.1",
        receiver: "0.0.9223372036854775807",
        amount: "5000000000000000000",
      })
    ).toBe(HBAR_BODY_LARGE_VALUES)
  })

  test("signs the keccak256 digest of the body", () => {
    expect(getDecodedWithdrawalId(decoded())).toBe(HBAR_DIGEST)
    expect(
      getDecodedWithdrawalId(
        decoded({ token: HEDERA_MAINNET_USDC_TOKEN_ID, amount: "1000000" })
      )
    ).toBe(USDC_DIGEST)
  })

  test.each([
    ["HBAR", {}],
    ["USDC", { token: HEDERA_MAINNET_USDC_TOKEN_ID, amount: "1000000" }],
  ])("carries a %s crypto transfer and nothing else", (_name, override) => {
    // The body's data variant selects the transaction type. Only field 14,
    // `cryptoTransfer`, is ever written, so no contract call (7, 8, 9, 22),
    // allowance (48, 49), ethereum transaction (50) or account creation (11)
    // can be signed.
    expect(
      topLevelFieldNumbers(getHederaVmTransactionBody(withdrawal(override)))
    ).toEqual([
      1, // transactionID
      2, // nodeAccountID
      3, // transactionFee
      4, // transactionValidDuration
      6, // memo
      14, // cryptoTransfer
    ])
  })

  test("nets the transfer entries to zero", () => {
    // The two entries are the same magnitude with opposite signs, so the debit
    // and credit cancel. Their zigzag encodings differ by exactly one.
    const amount = 500000000n
    const debit = 2n * amount - 1n // zigzag(-amount)
    const credit = 2n * amount // zigzag(amount)
    expect(credit - debit).toBe(1n)
    const encoded = body()
    expect(encoded).toContain(bytesToHex(varint(debit)).slice(2))
    expect(encoded).toContain(bytesToHex(varint(credit)).slice(2))
  })

  test.each([
    ["amount", { amount: "500000001" }],
    ["payer", { payer: "0.0.99" }],
    ["sender", { sender: "0.0.1002" }],
    ["receiver", { receiver: "0.0.2003" }],
    ["token", { token: HEDERA_MAINNET_USDC_TOKEN_ID }],
    ["nodeAccount", { nodeAccount: "0.0.4" }],
    ["validStart", { validStart: "1700000001.123456789" }],
    ["validDurationSeconds", { validDurationSeconds: 121 }],
    ["maxTransactionFee", { maxTransactionFee: "99999999" }],
  ])("binds %s into the signed body", (_field, override) => {
    expect(body(override)).not.toBe(HBAR_BODY)
    expect(getDecodedWithdrawalId(decoded(override))).not.toBe(HBAR_DIGEST)
  })
})

describe("hedera-vm withdrawal validation", () => {
  test.each(["payer", "sender", "receiver", "nodeAccount", "token"] as const)(
    "rejects an account alias for %s",
    (field) => {
      // Aliases carry no entity id, and transferring to one would have Hedera
      // auto-create a hollow account.
      expect(() =>
        getHederaVmTransactionBody(
          withdrawal({
            [field]: "0x5e7b112523f68d2f5e879db4eac51c6698a69304",
          })
        )
      ).toThrow(/account id/i)
    }
  )

  test("rejects a noncanonical account id", () => {
    expect(() =>
      getHederaVmTransactionBody(withdrawal({ receiver: "2002" }))
    ).toThrow()
  })

  test.each([
    ["1700000000", "no nanosecond part"],
    ["1700000000.5", "unpadded nanoseconds"],
    ["1700000000.1234567891", "10 nanosecond digits"],
  ])("rejects valid start %s (%s)", (validStart) => {
    expect(() =>
      getHederaVmTransactionBody(withdrawal({ validStart }))
    ).toThrow(/valid start/i)
  })
})

// Local varint encoder, used to assert on the amounts embedded in a body
// without reaching into the codec's internals.
const varint = (value: bigint): Uint8Array => {
  const bytes: number[] = []
  let remaining = value
  while (remaining >= 0x80n) {
    bytes.push(Number(remaining & 0x7fn) | 0x80)
    remaining >>= 7n
  }
  bytes.push(Number(remaining))
  return Uint8Array.from(bytes)
}

// Minimal protobuf reader over a body's top-level fields, so the structural
// assertions above check the encoding rather than the encoder.
const topLevelFieldNumbers = (message: Uint8Array): number[] => {
  const fieldNumbers: number[] = []
  let offset = 0

  const readVarint = (): bigint => {
    let value = 0n
    let shift = 0n
    for (;;) {
      if (offset >= message.length) {
        throw new Error("truncated varint")
      }
      const byte = message[offset++]
      value |= BigInt(byte & 0x7f) << shift
      if ((byte & 0x80) === 0) {
        return value
      }
      shift += 7n
    }
  }

  while (offset < message.length) {
    const tag = readVarint()
    fieldNumbers.push(Number(tag >> 3n))
    const wireType = Number(tag & 7n)
    if (wireType === 0) {
      readVarint()
    } else if (wireType === 2) {
      // Read the length before advancing: `offset += readVarint()` would use
      // the offset captured before the call and lose the length varint itself.
      const length = Number(readVarint())
      offset += length
    } else {
      throw new Error(`unexpected wire type ${wireType}`)
    }
  }

  return fieldNumbers
}
