#!/usr/bin/env tsx
/**
 * Mint one or more PKP wallets on a Chipotle account and print their
 * addresses.
 *
 * PKP key material is generated by Chipotle's DStack MPC, so minting needs a
 * live admin signer — it cannot be done as relayed calldata:
 *
 *   --mode api-key
 *     Managed (API-mode) account. Mints via the REST API with the admin
 *     `X-Api-Key`.
 *
 *   --mode chain-secured
 *     Wallet-owned account. The admin `--private-key` signs the EIP-712 mint
 *     request to the `*_with_signature` endpoint AND the follow-up on-chain
 *     `registerWalletDerivation` transaction.
 *
 * This is the flow to run BEFORE transferring a ChainSecured account to an
 * MPC/multisig owner: a multisig cannot produce the ECDSA signature the mint
 * endpoint requires, so provision every PKP you'll need up front, note the
 * addresses, then pass them to each action package's `setup` via `--pkp-id`.
 *
 * Usage:
 *   tsx scripts/create-pkp.ts --mode api-key       --account-api-key <key> [--count <n>] [--name <name>] [--description <text>]
 *   tsx scripts/create-pkp.ts --mode chain-secured --account-api-key <key> --private-key 0x... [--count <n>] [--name <name>] [--description <text>]
 */

import {
  createApiKeyBackend,
  createChainSecuredBackend,
  type SetupBackend,
  type SetupMode,
} from "../src/setup/index.js"

const USAGE =
  "Usage:\n" +
  "  tsx scripts/create-pkp.ts --mode api-key       --account-api-key <key> [--count <n>] [--name <name>] [--description <text>]\n" +
  "  tsx scripts/create-pkp.ts --mode chain-secured --account-api-key <key> --private-key 0x... [--count <n>] [--name <name>] [--description <text>]"

/** Read a CLI flag value accepting `--name value` or `--name=value`. */
function getOption(args: string[], name: string): string | undefined {
  const idx = args.indexOf(name)
  if (idx !== -1) {
    return args[idx + 1]
  }
  const prefix = `${name}=`
  return args.find((a) => a.startsWith(prefix))?.slice(prefix.length)
}

function fail(message: string): never {
  console.error(`${message}\n\n${USAGE}`)
  process.exit(1)
}

async function main() {
  const args = process.argv.slice(2)
  const mode = getOption(args, "--mode") as SetupMode | undefined
  const accountApiKey = getOption(args, "--account-api-key")
  const privateKey = getOption(args, "--private-key")
  const name = getOption(args, "--name") ?? "PKP"
  const description = getOption(args, "--description") ?? "Chipotle PKP"
  const countArg = getOption(args, "--count")

  if (mode !== "api-key" && mode !== "chain-secured") {
    fail("create-pkp requires --mode api-key or --mode chain-secured")
  }
  if (!accountApiKey) {
    fail("create-pkp requires --account-api-key <key>")
  }
  if (mode === "chain-secured" && !privateKey) {
    fail("--mode chain-secured requires --private-key <hex>")
  }

  let count = 1
  if (countArg !== undefined) {
    const parsed = Number(countArg)
    if (!Number.isInteger(parsed) || parsed < 1) {
      fail("--count must be a positive integer")
    }
    count = parsed
  }

  const backend: SetupBackend =
    mode === "api-key"
      ? createApiKeyBackend(accountApiKey)
      : createChainSecuredBackend({
          privateKey,
          accountApiKey,
          pkpName: name,
          pkpDescription: description,
        })

  console.log(`🔑 Minting ${count} PKP wallet(s)`)
  console.log(`   Mode:  ${backend.mode}`)
  if (mode === "chain-secured") {
    console.log(`   Name:  ${name}`)
  }
  console.log()

  const minted: string[] = []
  for (let i = 0; i < count; i++) {
    const { walletAddress } = await backend.createPkp()
    minted.push(walletAddress)
    console.log(`   ✓ [${i + 1}/${count}] ${walletAddress}`)
  }

  console.log()
  console.log("═══════════════════════════════════════════════════════")
  console.log(`  Minted ${minted.length} PKP wallet(s). Use as --pkp-id in setup:`)
  console.log("═══════════════════════════════════════════════════════")
  for (const address of minted) {
    console.log(`  ${address}`)
  }
  console.log()
}

main().catch((err) => {
  console.error("Error:", err instanceof Error ? err.message : err)
  process.exit(1)
})
