name: Main Branch

on:
  push:
    branches: main

jobs:
  run-tests:
    name: 'Run the tests'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        folders:
          ['smart-contracts', 'packages/hub-client', 'packages/hub-utils']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: yarn
        shell: bash

      - run: 'yarn build'
        shell: bash

      - name: Set workspace name
        id: workspace-name
        run: |
          if [[ "${{ matrix.folders }}" == packages/* ]]; then
            echo "WORKSPACE_NAME=$(echo ${{ matrix.folders }} | sed 's|packages/||')" >> $GITHUB_OUTPUT
          else
            echo "WORKSPACE_NAME=${{ matrix.folders }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: 'run lint'
        run: yarn workspace @relay-protocol/${{steps.workspace-name.outputs.WORKSPACE_NAME}} lint
        shell: bash

      - name: 'run tests'
        run: yarn workspace @relay-protocol/${{steps.workspace-name.outputs.WORKSPACE_NAME}} run test
        shell: bash
