name: Main Branch

on:
  push:
    branches: main

jobs:
  lint-build-test:
    name: Lint, build & test
    runs-on: ubuntu-24.04
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: |
          yarn build
          yarn workspace @relay-settlement/smart-contracts build

      - name: Run linters for all workspaces
        run: yarn workspaces foreach --all --topological-dev --exclude @relay-settlement/hub-monorepo run lint

      - name: Run workspace tests
        run: yarn workspaces foreach --all --topological-dev --exclude @relay-settlement/hub-monorepo run test
